### ISSUE TITLE
Not just a issue: Visualization of B-Spline curves in Jupyter Notebook

### ISSUE THREAD

**Issue by empet** [hyrodium/BasicBSpline.jl#172]
Hi,
Two days ago I came across your package, and I'm very excited because it is more mathematically oriented than  Dierkx or Interpolations. It is very useful for illustrating B-spline manifold properties in a course of Geometric Modeling or Approximation Theory.
I worked  on a few [examples of curves](https://nbviewer.org/github/empet/B-Spline-Manifolds/blob/main/Julia-B-spline-curves.ipynb)  and displayed them instantly in Jupyter Notebook, instead of saving them as  png files. They can be saved as raster or vector images with PlotlyJS.jl, too. 
Now I'm working on B-spline surfaces.

**Comment by hyrodium** [comment]
Thanks for the great examples! I'm really excited to see the interactive 3D plots of B-spline curve!

I'm also implementing the visualization with [BasicBSplineExporter.jl](https://github.com/hyrodium/BasicBSplineExporter.jl), but this is still in progress and it doesn't support outputs in Jupyter Notebook and plot pane in vscode for now.

I'm not much familiar with plotting, but It seems great to have a dependency on [RecipesBase.jl](https://docs.juliaplots.org/latest/recipes/). PRs are always welcome!

**Comment by empet** [comment]
RecipesBase.jl is mainly devised for Plots.jl. PlotlyJS.jl settings depend very much on the geometric object to be represented, and it's less suitable for recipes.
I plotted a few [B-spline surfaces](https://nbviewer.org/github/empet/B-Spline-Manifolds/blob/main/Julia-B-Spline-Surfaces.ipynb), too.  With each new graphic object computed with BasicBSpline.jl  I realize how great is this package!

**Comment by hyrodium** [comment]
The surface plotting is awesome!

>I realize how great is this package!

I'm really happy to hear that :heart:

**Comment by hyrodium** [comment]
The curve examples will be added in: https://github.com/hyrodium/BasicBSpline.jl/pull/181

**Comment by hyrodium** [comment]
With #183, B-spline curves can be visualized in Jupyter notebook.

![image](https://user-images.githubusercontent.com/7488140/160454273-5543c2b4-ec2d-42ad-b415-bd0a573cf7e7.png)

Note that some recipes for other types such as B-spline surface are not implemented yet. See https://github.com/hyrodium/BasicBSpline.jl/issues/184 for more information.
